name: Stryker Mutation Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  stryker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install Stryker
      run: dotnet tool install -g dotnet-stryker

    - name: Run Stryker
      working-directory: tests/ServiceableBus.Azure.Tests
      run: dotnet stryker -f stryker-config.json -O stryker-output

    - name: Upload Stryker Report
      uses: actions/upload-artifact@v4
      with:
        name: stryker-report
        path: stryker-output/reports/*.html